env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent: [1, 2, {"SwitchCase": 1}]
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - off
  no-console:
    - warn
  no-unused-vars:
    - warn
