rules:
  indent: [1, 2, {SwitchCase: 1}]
  comma-dangle: [0, always-multiline]
  quotes: [2, single, avoid-escape]
  linebreak-style: [1, unix]
  semi: [1, never]
  no-console: 1
  no-unused-vars: 1
env:
  es6: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
  modules: true
plugins:
  - react

react/jsx-no-undef: 2
