rules:
  indent: [2, 2, {SwitchCase: 1}]
  comma-dangle: [2, always-multiline]
  quotes: [2, single, avoid-escape]
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
env:
  es6: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
  modules: true
plugins:
  - react

react/jsx-no-undef: 2
